<!DOCTYPE html>
<html lang="es" ng-app="NoteWrangler">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Staying Sharp With Angularjs">
        <meta name="author" content="José Gabriel">

        <title>{% block title %}Inicio{% endblock %} - Staying Sharp with Angular.js</title>

        <!-- Bootstrap Core CSS -->
        <link href="/public/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

        <!-- Fontawesome CSS -->
        <link href="/public/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link href="/public/theme/css/heroic-features.css" rel="stylesheet">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        {% block stylesheets %}{% endblock %}

        <!-- jQuery -->
        <script src="/public/lib/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="/public/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- Angular.js -->
        <script src="/public/lib/angular/angular.min.js"></script>

    </head>

    <body>

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Wrangler</a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li>
                            <a href="#/users">Users</a>
                        </li>
                        <li>
                            <a href="#/notes">Notes</a>
                        </li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container -->
        </nav>

        <!-- Page Content -->
        <div class="container">

            <!-- Jumbotron Header -->
            <header class="jumbotron hero-spacer">
                <h1>Wrangler!</h1>
                <p>Staying sharp with Angular.js.</p>
                <p><a class="btn btn-primary btn-large">Go a head!</a>
                </p>
            </header>

            <hr>

            {% block content %}
            <div class="main-wrapper">
                <div ng-view></div>
            </div>
            {% endblock content %}

            <hr>

            <!-- Footer -->
            <footer>
                <div class="row">
                    <div class="col-lg-12">
                        <p>Copyright &copy; Your Website 2014</p>
                    </div>
                </div>
            </footer>

        </div>
        <!-- /.container -->

        {% block mainJavascript %}
        <!-- Angular route -->
        <script src="/public/lib/angular-route/angular-route.min.js"></script>
        <!-- Angular resource -->
        <script src="/public/lib/angular-resource/angular-resource.js"></script>
        {% endblock %}

        {% block javascript %}{% endblock %}

    </body>

</html>
